algorithmmmm/algorithm

221223/김승희/BOJ_5567_김승희.java
221223/김승희/PRG_프린터_김승희.java

✅ 공통문제 - 백준 5567 결혼식 (https://www.acmicpc.net/problem/5567)
✅ 공통문제 - 프로그래머스 프린터 (https://school.programmers.co.kr/learn/courses/30/lessons/42587)

221223 김승희 제출

---

221223/김아린/BOJ_12919_김아린.java
221223/김아린/BOJ_5567_김아린.java
221223/김아린/PRG_프린터_김아린.java

✅ 공통문제 - 백준 5567 결혼식 (https://www.acmicpc.net/problem/5567)
✅ 공통문제 - 프로그래머스 프린터 (https://school.programmers.co.kr/learn/courses/30/lessons/42587)
✅ 개인문제 - 백준 A와 B (https://www.acmicpc.net/problem/12919)

221223 김아린 제출

---

221229/김승희/BOJ_1303_김승희.java
221229/김승희/BOJ_18442_김승희.java
221229/김승희/PRG_피로도_김승희.java

✅ 공통문제 - 백준 1303 전쟁-전투 (https://www.acmicpc.net/problem/1303)
✅ 공통문제 - 프로그래머스 피로도(https://school.programmers.co.kr/learn/courses/30/lessons/87946)
✅ 개인문제 - 백준 18442 우체국1 (https://www.acmicpc.net/problem/18442)

221229 김승희 제출

---

221229/김아린/BOJ_1303_김아린.java
221229/김아린/BOJ_2493_김아린.java
221229/김아린/PRG_피로도_김아린.java

✅ 공통문제 - 백준 1303 결혼식 (https://www.acmicpc.net/problem/1303)
✅ 공통문제 - 프로그래머스 파로도 (https://school.programmers.co.kr/learn/courses/30/lessons/87946)
✅ 개인문제 - 백준 2493 탑 (https://www.acmicpc.net/problem/2493)

221229 김아린 제출

---

230107/김아린/BOJ_11052_김아린.java
230107/김아린/PRO_게임맵최단거리_김아린.java

✅ 공통문제 - 백준 11052 (https://www.acmicpc.net/problem/11052)
✅ 공통문제 - 프로그래머스 게임 맵 최단거리(https://school.programmers.co.kr/learn/courses/30/lessons/1844)
❎ 개인문제 - 백준 1744 수묶기(https://www.acmicpc.net/problem/1744) -> 계속 틀려서 안풀림..😥

230107 김아린 제출

---

230114/김아린/BOJ_13335_김아린.java
230114/김아린/PRO_42898_김아린.java

✅ 공통문제 - 백준 11052 (https://www.acmicpc.net/problem/13335)
❎ 공통문제 - 프로그래머스 - 등굣길(https://school.programmers.co.kr/learn/courses/30/lessons/42898) -> 안풀림...

20230114 김아린 제출

---

230114/김승희/BOJ_13335_김승희.java
230114/김승희/PRG_등굣길_김승희.java

✅ 공통문제 - 백준 11052 (https://www.acmicpc.net/problem/13335)
✅ 공통문제 - 프로그래머스 - 등굣길(https://school.programmers.co.kr/learn/courses/30/lessons/42898)

230114 김승희 제출

---

230121/김승희/BOJ_17298_김승희.java
230121/김승희/PRG_순위_김승희.java

✅ 공통문제 - 백준 오큰수(https://www.acmicpc.net/problem/17298)
✅ 공통문제 - 프로그래머스 순위(https://school.programmers.co.kr/learn/courses/30/lessons/49191)

230121김승희 제출

---

230121/김아린/BOJ_17298_김아린.java
230121/김아린/PRG_49191_김아린.java

✅ 공통문제 - 백준 오큰수(https://www.acmicpc.net/problem/17298)
✅ 공통문제 - 프로그래머스 순위(https://school.programmers.co.kr/learn/courses/30/lessons/49191)

20230121 김아린 제출

---

230128/BOJ_16987_김승희.java
230128/PRG_양궁대회_김승희.java

✅ 백준: 계란으로 계란치기(https://www.acmicpc.net/problem/16987)
❎ 프로그래머스: 양궁대회(https://school.programmers.co.kr/learn/courses/30/lessons/92342)

230128 김승희 제출

---

230128/김아린/BOJ_16987_김아린.java

❎ 백준: 계란으로 계란치기(https://www.acmicpc.net/problem/16987)
❎ 프로그래머스: 양궁대회(https://school.programmers.co.kr/learn/courses/30/lessons/92342)

230128 김아린 제출

---

230206/김아린/BOJ_14719_김아린.java
230206/김아린/PRO_72412_김아린.java

✅ 백준: 빗물(https://www.acmicpc.net/problem/14719)
❎ 프로그래머스: 순위검색(https://school.programmers.co.kr/learn/courses/30/lessons/72412)

230206 김아린 제출

---

230206/김승희/BOJ_14719_김승희.java
230206/김승희/PRG_순위검색_김승희.java
230206/김승희/PRG_순위검색_김승희.py

✅ 백준: 빗물(https://www.acmicpc.net/problem/14719)
❎ 프로그래머스: 순위검색(https://school.programmers.co.kr/learn/courses/30/lessons/72412)

230206 김승희 제출

---

230429/김아린/PRO_비밀지도_김아린.java
230429/김아린/PRO_주차요금계산_김아린.java

✅ 프로그래머스: 주차 요금 계산(https://school.programmers.co.kr/learn/courses/30/lessons/92341)
❌ 프로그래머스: 더 맵게(https://school.programmers.co.kr/learn/courses/30/lessons/17681)

230429 김아린 제출

---

230429/백자민/PRG_42626_백자민.java
230429/백자민/SWEA_5643_백자민.java
230429/백자민/SWEA_5656_백자민.java

✅ 프로그래머스: 더 맵게(https://school.programmers.co.kr/learn/courses/30/lessons/42626)
✅ SWEA: 키 높이(https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWXQsLWKd5cDFAUo)
✅ SWEA: 벽돌 깨기(https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWXRQm6qfL0DFAUo)

230329 백자민 제출

---

230506/김아린/PRO_압축_김아린.java
230506/김아린/PRO_컬러링북_김아린.java
230513/김아린/PRO_프렌즈4블록_김아린.java

0506
✅ 프로그래머스 : 압축(https://school.programmers.co.kr/learn/courses/30/lessons/17684)
✅ 프로그래머스 : 카카오프렌즈 컬러링북(https://school.programmers.co.kr/learn/courses/30/lessons/1829)
0513
✅ 프로그래머스 : 프렌즈4블록(https://school.programmers.co.kr/learn/courses/30/lessons/17679)

230506 김아린 제출

---

230527/김승희/PRO_숫자게임_김승희.py
230527/김승희/PRO_징검다리건너기_김승희.py

✅ 프로그래머스: 징검다리 건너기(https://school.programmers.co.kr/learn/courses/30/lessons/64062)
✅ 프로그래머스: 숫자게임(https://school.programmers.co.kr/learn/courses/30/lessons/12987)

230527 김승희 제출

---

230606/김승희/BOJ_꿀벌승연이_김승희.java
230606/김승희/PRO_귤고르기_김승희.java
230606/김승희/PRO_영어끝말잇기_김승희.py

✅ 프로그래머스: 귤 고르기(https://school.programmers.co.kr/learn/courses/30/lessons/138476)
✅ 프로그래머스: 영어 끝말잇기(https://school.programmers.co.kr/learn/courses/30/lessons/12981)
❌ 백준 : 꿀벌 승연이(https://www.acmicpc.net/problem/23083)

230606 김승희 제출

---

230606/김아린/BOJ_꿀벌승연이.java
230606/김아린/PRO_뉴스클러스터링.java
230606/김아린/PRO_단체사진찍기.java
230606/김아린/PRO_파일명정렬.java

✅ 프로그래머스: 뉴스 클러스터링(https://school.programmers.co.kr/learn/courses/30/lessons/17677)
✅ 프로그래머스: 단체 사진 찍기(https://school.programmers.co.kr/learn/courses/30/lessons/1835)
✅ 프로그래머스: 파일명 정렬(https://school.programmers.co.kr/learn/courses/30/lessons/17686)
❌ 백준 : 꿀벌 승연이(https://www.acmicpc.net/problem/23083)

230606 김아린 제출

---

230613/김승희/BOJ_23085_판치기.java
230613/김승희/PRO__야근지수.py
230613/김승희/PRO_스티커모으기(2).py
230613/김승희/PRO_여행경로.py

✅ 프로그래머스: 야근지수 (https://school.programmers.co.kr/learn/courses/30/lessons/12927)
✅ 프로그래머스: 스티커 모으기(2)(https://school.programmers.co.kr/learn/courses/30/lessons/12971#)
✅ 프로그래머스: 여행경로(https://school.programmers.co.kr/learn/courses/30/lessons/43164)
✅ 백준 : 판치기(https://www.acmicpc.net/problem/23085)

230613 김승희 제출

---

230621/백자민/BOJ_17182_백자민.java
230621/백자민/BOJ_2230_백자민.java
230621/백자민/BOJ_2531_백자민.java
230621/백자민/BOJ_2668_백자민.java
230621/백자민/BOJ_6198_백자민.java

✅ : 백준-17182(https://www.acmicpc.net/problem/17182)
✅ : 백준-2230(https://www.acmicpc.net/problem/2230)
✅ : 백준-2531(https://www.acmicpc.net/problem/2531)
✅ : 백준-2668(https://www.acmicpc.net/problem/2668)
✅ : 백준-6198(https://www.acmicpc.net/problem/6198)

230621 백자민 제출

---

230621/김승희/BOJ_10800_김승희.java
230621/김승희/BOJ_2668_김승희.java
230621/김승희/PRG_1차캐시_김승희.py
230621/김승희/PRG_튜플_김승희.py

✅ 프로그래머스: 1차 [캐시](https://school.programmers.co.kr/learn/courses/30/lessons/17680)
✅ 프로그래머스: 튜플 (https://school.programmers.co.kr/learn/courses/30/lessons/64065)
✅ 백준 : 숫자고르기(https://www.acmicpc.net/problem/2668)
✅ 백준 : 컬러볼(https://www.acmicpc.net/problem/10800)

230621 김승희 제출

---

230627/김승희/BOJ_18808_김승희.java
230627/김승희/PRG_기지국설치_김승희.py
230627/김승희/PRG_멀리뛰기_김승희.py
230627/김승희/PRG_최고의집합_김승희.py
230627/김승희/PRG_호텔대실_김승희.py

✅ 프로그래머스: 호텔 대실(https://school.programmers.co.kr/learn/courses/30/lessons/155651#)
✅ 프로그래머스: 최고의 집합 (https://school.programmers.co.kr/learn/courses/30/lessons/12938)
✅ 프로그래머스: 멀리뛰기 (https://school.programmers.co.kr/learn/courses/30/lessons/12914)
✅ 프로그래머스: 기지국 설치(https://school.programmers.co.kr/learn/courses/30/lessons/12979)
✅ 백준 : 스티커 붙이기(https://www.acmicpc.net/problem/18808)

230627 김승희 제출

---

230627/백자민/BOJ_17266_백자민.java
230627/백자민/BOJ_18808_백자민.java
230627/백자민/BOJ_2023_백자민.java
230627/백자민/PRG_92343_백자민.java

✅ 백준(공통문제): 스티커 붙이기(https://www.acmicpc.net/problem/18808)
✅ 백준: 신기한 소수(https://www.acmicpc.net/problem/2023)
✅ 백준: 어두운 굴다리(https://www.acmicpc.net/problem/17266)
✅ 프로그래머스: 양과 늑대(https://school.programmers.co.kr/learn/courses/30/lessons/92343)

230627 백자민 제출

---

230704/백자민/BOJ_12015_백자민.java
230704/백자민/BOJ_14002_백자민.java
230704/백자민/BOJ_2110_백자민.java
230704/백자민/PRG_67258_백자민.java
230704/백자민/PRG_92344_백자민.java

✅ 프로그래머스(공통문제): 보석 쇼핑 (https://school.programmers.co.kr/learn/courses/30/lessons/67258)
✅ 프로그래머스: 파괴되지 않은 건물 (https://school.programmers.co.kr/learn/courses/30/lessons/92344)
✅ 백준: 가장 긴 증가하는 부분 수열2 (https://www.acmicpc.net/problem/12015)
✅ 백준: 가장 긴 증가하는 부분 수열4 (https://www.acmicpc.net/problem/14002)
✅ 백준: 공유기 설치 (https://www.acmicpc.net/problem/2110)

230706 백자민 제출

---

230704/김승희/PRG_괄호회전하기_김승희.py
230704/김승희/PRG_다단계칫솔판매_김승희.py
230704/김승희/PRG_보석쇼핑_김승희.py
230704/김승희/PRG_부대복귀_김승희.py

✅ 프로그래머스: 괄호 회전하기(https://school.programmers.co.kr/learn/courses/30/lessons/76502)
✅ 프로그래머스: 다단계 칫솔 판매 (https://school.programmers.co.kr/learn/courses/30/lessons/77486)
✅ 프로그래머스: 보석 쇼핑 (https://school.programmers.co.kr/learn/courses/30/lessons/67258)
✅ 프로그래머스: 부대복귀(https://school.programmers.co.kr/learn/courses/30/lessons/132266)

230704 김승희 제출

---

230711/김승희/BOJ_1135_김승희.java
230711/김승희/BOJ_16472_김승희.java
230711/김승희/BOJ_20006_김승희.java
230711/김승희/BOJ_2096_김승희.java
230711/김승희/PRG_경주로건설_김승희.py

✅ 프로그래머스: 경주로 건설(https://school.programmers.co.kr/learn/courses/30/lessons/67259)
✅ 백준: 내려가기(https://www.acmicpc.net/problem/2096)
✅ 백준: 고냥이 (https://www.acmicpc.net/problem/16472)
✅ 백준: 랭킹전대기열 (https://www.acmicpc.net/problem/20006)
✅ 백준: 뉴스전하기 (https://www.acmicpc.net/problem/1135)

230711 김승희 제출

---

230719/김승희/BOJ_1445_김승희.java
230719/김승희/BOJ_2234_김승희.java
230719/김승희/BOJ_2631_김승희.java
230719/김승희/PRG_셔틀버스_김승희.py

✅ 프로그래머스: 셔틀 버스 (https://school.programmers.co.kr/learn/courses/30/lessons/17678)
✅ 백준: 줄세우기(https://www.acmicpc.net/problem/2631)
✅ 백준: 성곽 (https://www.acmicpc.net/problem/2234)
✅ 백준: 일요일 아침의 데이트(https://www.acmicpc.net/problem/1445)

230719 김승희 제출

---

230719/백자민/BOJ_1238_백자민.java
230719/백자민/BOJ_2138_백자민.java
230719/백자민/BOJ_2234_백자민.java
230719/백자민/BOJ_2638_백자민.java
230719/백자민/PRG_118669_백자민.java

✅ 백준(공통문제): 성곽(https://www.acmicpc.net/problem/2234)
✅ 프로그래머스: 등산코스 정하기(https://school.programmers.co.kr/learn/courses/30/lessons/118669)
✅ 백준: 치즈(https://www.acmicpc.net/problem/2638)
✅ 백준: 전구와 스위치(https://www.acmicpc.net/problem/2138)
✅ 백준: 파티(https://www.acmicpc.net/problem/1238)

230719 백자민 제출

---

230719/김아린/BOJ_벽부수고이동하기_김아린.java
230719/김아린/BOJ_성곽_김아린.java
230719/김아린/PRO_광물캐기_김아린.java
230719/김아린/PRO_요격시스템_김아린.java

✅ 프로그래머스: 요격시스템 (https://school.programmers.co.kr/learn/courses/30/lessons/181188)
✅ 프로그래머스: 광물캐기 (https://school.programmers.co.kr/learn/courses/30/lessons/172927)
❌ 백준: 성곽 (https://www.acmicpc.net/problem/2234)
❌ 백준: 성곽 (https://www.acmicpc.net/problem/2206)

20230719 김아린 제출

---

230725/백자민/BOJ_14658_백자민.java
230725/백자민/BOJ_1647_백자민.java
230725/백자민/BOJ_23743_백자민.java
230725/백자민/PRG_118668_백자민.java

✅ 백준(공통문제): 방탈출 (https://www.acmicpc.net/problem/23743)
✅ 백준: 도시 분할 계획 (https://www.acmicpc.net/problem/1647)
✅ 백준: 하늘에서 별똥별이 빗발친다 (https://www.acmicpc.net/problem/14658)
✅ 프로그래머스: 코딩 테스트 공부 (https://school.programmers.co.kr/learn/courses/30/lessons/118668)

230725 백자민 제출

---

230725/김승희/BOJ_23743_김승희.java
230725/김승희/PRG_가장긴팰린드롬_김승희.py
230725/김승희/PRG_자물쇠와열쇠_김승희.py
230725/김승희/PRG_표편집_김승희.java
230725/김승희/PRG_행렬테두리회전하기_김승희.py

✅ 프로그래머스: 가장 긴 팰린드롬(https://school.programmers.co.kr/learn/courses/30/lessons/12904)
✅ 프로그래머스: 행렬 테두리 회전하기 (https://school.programmers.co.kr/learn/courses/30/lessons/77485)
✅ 프로그래머스: 표 편집 (https://school.programmers.co.kr/learn/courses/30/lessons/81303?language=java#)
✅ 프로그래머스: 자물쇠와 열쇠(https://school.programmers.co.kr/learn/courses/30/lessons/60059#)
✅ 백준: 방탈출(https://www.acmicpc.net/problem/23743)

230725 김승희 제출

---

230801/김승희/BOJ_13459_김승희.java
230801/김승희/BOJ_13460_김승희.java
230801/김승희/BOJ_22868_김승희.java
230801/김승희/PRG_다리를지나는트럭_김승희.py
230801/김승희/PRG_스킬트리_김승희.py

✅ 프로그래머스: 스킬 트리 (https://school.programmers.co.kr/learn/courses/30/lessons/49993)
✅ 프로그래머스: 다리를 지나는 트럭 (https://school.programmers.co.kr/learn/courses/30/lessons/42583)
✅ 백준: 산책(small)(https://www.acmicpc.net/problem/22868)
✅ 백준: 구슬탈출 (https://www.acmicpc.net/problem/13459)
✅ 백준: 구슬탈출 2 (https://www.acmicpc.net/problem/13460)

230801 김승희 제출

---

230801/백자민/BOJ_11437_백자민.java
230801/백자민/BOJ_13459_백자민.java
230801/백자민/BOJ_9465_백자민.java
230801/백자민/PRG_150366_백자민.java

✅ 백준(공통문제): 구슬 탈출 (https://www.acmicpc.net/problem/13459)
✅ 백준: 스티커 (https://www.acmicpc.net/problem/9465)
✅ 백준: LCA (https://www.acmicpc.net/problem/11437)
✅ 프로그래머스: 표 병합 (https://school.programmers.co.kr/learn/courses/30/lessons/150366)

230801 백자민 제출

---

230808/백자민/BOJ_11967_백자민.java
230808/백자민/BOJ_1929_백자민.java
230808/백자민/PRG_150365_백자민.java
230808/백자민/PRG_72414_백자민.java
230808/백자민/PRG_92335_백자민.java

✅ 백준(공통문제): 불켜기 (https://www.acmicpc.net/problem/11967)
✅ 프로그래머스: 광고 삽입 (https://school.programmers.co.kr/learn/courses/30/lessons/72414)
✅ 프로그래머스: 미로 탈출 명령어 (https://school.programmers.co.kr/learn/courses/30/lessons/150365)
✅ 프로그래머스: k진수에서 소수 개수 구하기 (https://school.programmers.co.kr/learn/courses/30/lessons/92335)

230808 백자민 제출

---

230808/김승희/BOJ_11967_불켜기_김승희.java
230808/김승희/BOJ_1915_가장큰정사각형_김승희.java
230808/김승희/BOJ_25636_소방차_김승희.java
230808/김승희/PRG_연속펄스부분수열의합_김승희.py

✅ 백준: 불켜기(https://www.acmicpc.net/problem/11967)
✅ 백준: 소방차(https://www.acmicpc.net/problem/25636)
✅ 백준: 가장 큰 정사각형(https://www.acmicpc.net/problem/1915)
✅ 프로그래머스: 연속 펄스 부분 수열의 합(https://school.programmers.co.kr/learn/courses/30/lessons/161988)

230808 김승희 제출

---

230808/김아린/BOJ_불켜기_김아린.java
230808/김아린/PRO_시소짝꿍_김아린.java
230808/김아린/PRO_주식가격_김아린.java
230808/김아린/PRO_호텔대실_김아린.java

✅ 백준: 불켜기(https://www.acmicpc.net/problem/11967)
✅ 프로그래머스 : 주식가격(https://school.programmers.co.kr/learn/courses/30/lessons/42584)
✅ 프로그래머스 : 호텔 대실(https://school.programmers.co.kr/learn/courses/30/lessons/155651)
✅ 프로그래머스 : 시소 짝꿍(https://school.programmers.co.kr/learn/courses/30/lessons/152996)

230808 김아린 제출

---

230815/백자민/BOJ_12865_백자민.java
230815/백자민/BOJ_16472_백자민.java
230815/백자민/BOJ_2169_백자민.java
230815/백자민/PRG_148653_백자민.java
230815/백자민/PRG_86052_백자민.java

✅ 백준(공통문제): 로봇 조종하기 (https://www.acmicpc.net/problem/2169)
✅ 백준: 고냥이 (https://www.acmicpc.net/problem/16472)
✅ 프로그래머스: 빛의 경로 사이클 (https://school.programmers.co.kr/learn/courses/30/lessons/86052)
✅ 프로그래머스: 마법의 엘리베이터 (https://school.programmers.co.kr/learn/courses/30/lessons/148653)

230815 백자민 제출

---

230815/김아린/BOJ_로봇조종하기_김아린.java
230815/김아린/BOJ_연산자끼워넣기3_김아린.java
230815/김아린/PRO_무인도여행.java
230815/김아린/PRO_유사칸토어비트열_김아린.java

✅ 백준: 로봇 조종하기(https://www.acmicpc.net/problem/2169)
✅ 백준: 연산자 끼워넣기 (3)(https://www.acmicpc.net/problem/15659)
✅ 프로그래머스 : 무인도 여행(https://school.programmers.co.kr/learn/courses/30/lessons/154540)
✅ 프로그래머스 : 유사 칸토어 비트열(https://school.programmers.co.kr/learn/courses/30/lessons/148652)

230815 김아린 제출

---

230815/김승희/BOJ_14938_김승희.java
230815/김승희/BOJ_19542_김승희.java
230815/김승희/BOJ_2169_김승희.java
230815/김승희/PRG_이모티콘할인행사_김승희.java

✅ 프로그래머스: 이모티콘 할인행사(https://school.programmers.co.kr/learn/courses/30/lessons/150368)
✅ 백준 : 서강그라운드(https://school.programmers.co.kr/learn/courses/30/lessons/14938)
✅ 백준 : 전단지돌리기(https://school.programmers.co.kr/learn/courses/30/lessons/19542)
❌ 백준 : 로봇 조종하기(https://www.acmicpc.net/problem/2169)

230815 김승희 제출

---

230822/김승희/BOJ_1256_김승희.py
230822/김승희/BOJ_18427_김승희.java
230822/김승희/BOJ_1976_김승희.java
230822/김승희/BOJ_7490_김승희.java
230822/김승희/PRG_미로탈출명령어_김승희.java

✅ 프로그래머스: 미로 탈출 명령어(https://school.programmers.co.kr/learn/courses/30/lessons/150365)
✅ 백준 : 여행 가자(https://www.acmicpc.net/problem/1976)
✅ 백준 : 함께 블록 쌓기(https://www.acmicpc.net/problem/18427)
✅ 백준 : 0 만들기(https://www.acmicpc.net/problem/7490)
✅ 백준 : 사전(https://www.acmicpc.net/problem/1256)

230822 김승희 제출

---

230822/김아린/BOJ_사전_김아린.java
230822/김아린/PRO_n진수게임_김아린.java
230822/김아린/PRO_스킬트리_김아린.java
230822/김아린/PRO_아이템줍기_김아린.java

✅ 프로그래머스 : 스킬트리(https://school.programmers.co.kr/learn/courses/30/lessons/49993)
✅ 프로그래머스 : n진수 게임(https://school.programmers.co.kr/learn/courses/30/lessons/17687)
✅ 프로그래머스 : 아이템 줍기(https://school.programmers.co.kr/learn/courses/30/lessons/87694)
❌ 백준 : 사전(https://school.programmers.co.kr/learn/courses/30/lessons/148652)

20230822 김아린 제출

---

230829/김승희/BOJ_16724_김승희.java
230829/김승희/BOJ_1956_김승희.java
230829/김승희/BOJ_2879_김승희.java

✅ 백준(공통문제): 피리 부는 사나이 (https://www.acmicpc.net/problem/16724)
✅ 백준: 운동 (https://www.acmicpc.net/problem/1956)
✅ 백준: 코딩은 예쁘게 (https://www.acmicpc.net/problem/2879)

230829 김승희 제출

---

230829/BOJ_10830_백자민.java
230829/BOJ_1194_백자민.java
230829/BOJ_16724_백자민.java
230829/PRG_150368_백자민.java

✅ 백준(공통문제): 피리 부는 사나이 (https://www.acmicpc.net/problem/16724)
✅ 백준: 행렬 제곱 (https://www.acmicpc.net/problem/10830)
✅ 백준: 달이 차오른다, 가자 (https://www.acmicpc.net/problem/1194)
✅ 프로그래머스: 이모티콘 할인행사 (https://school.programmers.co.kr/learn/courses/30/lessons/150368)

230829 백자민 제출

---

230829/김아린/BOJ_벽부수고이동하기2_김아린.java
230829/김아린/BOJ_벽부수고이동하기_김아린.java
230829/김아린/BOJ_피리부는사나이_김아린.java
230829/김아린/PRO_이중우선순위큐_김아린.java

✅ 프로그래머스 : 이중우선순위큐(https://school.programmers.co.kr/learn/courses/30/lessons/42628)
✅ 백준 : 피리 부는 사나이(https://www.acmicpc.net/problem/16724)
✅ 백준 : 벽부수고 이동하기(https://www.acmicpc.net/problem/2206)
✅ 백준 : 벽부수고 이동하기2(https://www.acmicpc.net/problem/14442)

230829 김아린 제출

---

230906/김승희/BOJ_1106_김승희.java
230906/김승희/BOJ_17609_김승희.java
230906/김승희/BOJ_25319_김승희.java
230906/김승희/BOJ_27114_김승희.java

❌ 백준(공통문제): Twitch Plays VIIIbit Explorer(https://www.acmicpc.net/problem/25319)
✅ 백준: 호텔 (https://www.acmicpc.net/problem/1106)
✅ 백준: 회문(https://www.acmicpc.net/problem/17609)
✅ 백준: 조교의 맹연습(https://www.acmicpc.net/problem/27114)

230906 김승희 제출

---

230906/김아린/BOJ_Twitch Plays VIIIbit Explorer.java
230906/김아린/PRG_이진 변환 반복하기.java
230906/김아린/PRG_택배 배달과 수거하기.java
230906/김아린/PRG_테이블 해시 함수.java

✅ 프로그래머스 : 택배 배달과 수거하기(https://school.programmers.co.kr/learn/courses/30/lessons/150369)
✅ 프로그래머스 : 이진 변환 반복하기(https://school.programmers.co.kr/learn/courses/30/lessons/70129)
✅ 프로그래머스 : 테이블 해시 함수(https://school.programmers.co.kr/learn/courses/30/lessons/147354)
❌ 백준 : Twitch Plays VIIIbit Explorer(https://www.acmicpc.net/problem/25319)

230906 김아린 제출

---

230912/김승희/BOJ_11559_김승희.java
230912/김승희/PRG_PCCP모의고사2회1번_김승희.java
230912/김승희/PRG_PCCP모의고사2회2번_김승희.java
230912/김승희/PRG_PCCP모의고사2회3번_김승희.java
230912/김승희/PRG_PCCP모의고사2회4번_김승희.java

✅ 백준(공통문제): Puyo Puyo (https://www.acmicpc.net/problem/11559)
✅ 프로그래머스 PCCP 모의고사 2회 (https://school.programmers.co.kr/learn/courses/15009/15009-pccp-%EB%AA%A8%EC%9D%98%EA%B3%A0%EC%82%AC-2%ED%9A%8C)

230912 김승희 제출

---

230912/BOJ_11559_백자민.java
230912/BOJ_15666_백자민.java
230912/BOJ_18500_백자민.java

✅ 백준(공통문제): Puyo Puyo (https://www.acmicpc.net/problem/11559)
✅ 백준: 미네랄2 (https://www.acmicpc.net/problem/18500)
✅ 백준: N과M(12) (https://www.acmicpc.net/problem/15666)

230912 백자민 제출

---

230919/김승희/BOJ_1261_김승희.java
230919/김승희/BOJ_17835_김승희.java
230919/김승희/BOJ_7682_김승희.java

✅ 백준(공통문제): 알고스팟 (https://www.acmicpc.net/problem/1261)
✅ 백준: 틱택토 (https://www.acmicpc.net/problem/7682)
✅ 백준: 면접보는 승범이네 (https://www.acmicpc.net/problem/17835)

230919 김승희 제출

---

230919/김아린/BOJ_알고스팟_김아린.java
230919/김아린/PRG_양과늑대_김아린.java
230919/김아린/PRG_이모티콘할인행사_김아린.java

✅ 프로그래머스 : 이모티콘 할인행사(https://school.programmers.co.kr/learn/courses/30/lessons/150368)
✅ 프로그래머스 : 양과 늑대(https://school.programmers.co.kr/learn/courses/30/lessons/92343)
✅ 백준 : 알고 스팟(https://www.acmicpc.net/problem/1261)

230919 김아린 제출

---

230926/김승희/BOJ_14658_김승희.java
230926/김승희/BOJ_16974_김승희.java
230926/김승희/BOJ_20055_김승희.java

✅ 백준(공통문제): 컨베이어벨트 위의 로봇 (https://www.acmicpc.net/problem/20055)
✅ 백준: 하늘에서 별똥별이 빗발친다 (https://www.acmicpc.net/problem/14658)
✅ 백준: 레벨 햄버거 (https://www.acmicpc.net/problem/16974)

230926 김승희 제출

---

230926/백자민/BOJ_11779_백자민.java
230926/백자민/BOJ_20055_백자민.java
230926/백자민/BOJ_2533_백자민.java

✅ 백준(공통문제): 컨베이어 벨트 위의 로봇 (https://www.acmicpc.net/problem/20055)
✅ 백준: 최소비용 구하기 2 (https://www.acmicpc.net/problem/11779)
✅ 백준: 사회망 서비스(SNS) (https://www.acmicpc.net/problem/2533)

230926 백자민 제출

---

230926/김아린/BOJ_인구이동_김아린.java
230926/김아린/BOJ_좋은수열_김아린.java
230926/김아린/BOJ_컨베이어벨트위의로봇_김아린.java

✅ 백준 : 컨베이어 벨트 위의 로봇(https://www.acmicpc.net/problem/20055)
✅ 백준 : 좋은 수열(https://www.acmicpc.net/problem/2661)
✅ 백준 : 인구 이동(https://www.acmicpc.net/problem/16234)

230926 김아린 제출

---

231010/김승희/BOJ_10800_김승희.java
231010/김승희/BOJ_13144_김승희.java
231010/김승희/BOJ_18500_김승희.java
231010/김승희/BOJ_21609_김승희.java
231010/김승희/BOJ_9082_김승희.java

✅ 백준(공통문제): 컬러볼 (https://www.acmicpc.net/problem/10800)
✅ 백준: List of Unique Numbers (https://www.acmicpc.net/problem/13144)
✅ 백준: 미네랄2 (https://www.acmicpc.net/problem/18500)
✅ 백준: 지뢰 찾기 (https://www.acmicpc.net/problem/9082)
✅ 백준: 상어 중학교 (https://www.acmicpc.net/problem/21609)

231010 김승희 제출

---

231010/백자민/BOJ_10800_백자민.java
231010/백자민/BOJ_18428_백자민.java
231010/백자민/BOJ_4179_백자민.java

✅ 백준(공통문제): 컬러볼(https://www.acmicpc.net/problem/10800)
✅ 백준: 감시 피하기(https://www.acmicpc.net/problem/18428)
✅ 백준: 불!(https://www.acmicpc.net/problem/4179)

231010 백자민 제출

---

231009/김아린/BOJ_스도쿠_김아린.java
231009/김아린/BOJ_컬러볼_김아린.java

✅ 백준 : 스도쿠(https://www.acmicpc.net/problem/2580)
✅ 백준 : 컬러볼(https://www.acmicpc.net/problem/10800)

231010김아린 제출

---

231017/김승희/BOJ_14442_김승희.java
231017/김승희/BOJ_20437_김승희.java
231017/김승희/BOJ_2179_김승희.java
231017/김승희/BOJ_23290_김승희.java

✅ 백준(공통문제): 비슷한 단어(https://www.acmicpc.net/problem/2179)
✅ 백준: 벽부수고 이동하기 2(https://www.acmicpc.net/problem/14442)
✅ 백준: 문자열 게임 2(https://www.acmicpc.net/problem/20437)
✅ 백준: 마법사 상어와 복제(https://www.acmicpc.net/problem/23290)

231017 김승희 제출

---

231024/백자민/BOJ_10159_백자민.java
231024/백자민/BOJ_10282_백자민.java
231024/백자민/BOJ_11561_백자민.java
231024/백자민/BOJ_15591_백자민.java

✅ 백준(공통문제): 저울 (https://www.acmicpc.net/problem/10159)
✅ 백준: MooTube(Silver) (https://www.acmicpc.net/problem/15591)
✅ 백준: 해킹 (https://www.acmicpc.net/problem/10282)
✅ 백준: 징검다리 (https://www.acmicpc.net/problem/11561)

231024 백자민 제출

---

231024/김아린/BOJ_저울_김아린.java
231024/김아린/PRG_두큐합같게만들기_김아린.java
231024/김아린/PRG_조이스틱_김아린.java

✅ 백준 : 저울(https://www.acmicpc.net/problem/10159)
✅ 프로그래머스 : 두 큐 합 같게 만들기(https://school.programmers.co.kr/learn/courses/30/lessons/118667)
✅ 프로그래머스 : 조이스틱(https://school.programmers.co.kr/learn/courses/30/lessons/42860)

231024 김아린 제출

---

231031/김승희/BOJ_10655_김승희.java

✅ 백준 : 마라톤1(https://www.acmicpc.net/problem/10655)

231031 김승희 제출

---

231031/백자민/BOJ_1949_백자민.java
231031/백자민/PRG_154539_백자민.java
231031/백자민/PRG_43238_백자민.java

✅ 백준(공통문제): 우수 마을(https://www.acmicpc.net/problem/1949)
✅ 프로그래머스: 입국 심사(https://school.programmers.co.kr/learn/courses/30/lessons/43238)
✅ 프로그래머스: 뒤에 있는 큰 수 찾기(https://school.programmers.co.kr/learn/courses/30/lessons/154539)

231031 백자민 제출

---

231031/김아린/BOJ_상범빌딩_김아린.java
231031/김아린/BOJ_우수마을_김아린.java
231031/김아린/BOJ_트리와쿼리_김아린.java

✅ 백준 : 상범빌딩(https://www.acmicpc.net/problem/6593)
✅ 백준 : 트리와 쿼리(https://www.acmicpc.net/problem/15681)
✅ 백준 : 우수 마을(https://www.acmicpc.net/problem/1949)

231031 김아린 제출

---

231114/김승희/BOJ_10159_김승희.java
231114/김승희/BOJ_11497_김승희.java
231114/김승희/BOJ_18430_김승희.java
231114/김승희/PRG_카펫_김승희.java

❌ 백준(공통문제): 무기 공학(https://www.acmicpc.net/problem/18430)
✅ 백준: 통나무 건너뛰기(https://www.acmicpc.net/problem/11497)
✅ 백준: 저울(https://www.acmicpc.net/problem/10159)
✅ 프로그래머스: 성격 유형 검사하기(https://school.programmers.co.kr/learn/courses/30/lessons/42842)

231114 김승희 제출

---

231114/김아린/BOJ_LCS2_김아린.java
231114/김아린/BOJ_무기공학_김아린.java
231114/김아린/PRG_귤고르기_김아린.java
231114/김아린/PRG_연속부분수열합의개수_김아린.java
231114/김아린/PRG_할인행사_김아린.java

✅ 백준 : 무기공학(https://www.acmicpc.net/problem/18430)
✅ 백준 : LCS2(https://www.acmicpc.net/problem/9252)
✅ 프로그래머스 : 귤고르기(https://school.programmers.co.kr/learn/courses/30/lessons/138476)
✅ 프로그래머스 : 연속 부분 수열 합의 개수(https://school.programmers.co.kr/learn/courses/30/lessons/131701)
✅ 프로그래머스 : 할인 행사(https://school.programmers.co.kr/learn/courses/30/lessons/131127)

231114 김아린 제출

---

231121/김승희/BOJ_14846_김승희.java
231121/김승희/BOJ_2170_김승희.java
231121/김승희/BOJ_3190_김승희.java

✅ 백준: 뱀(https://www.acmicpc.net/problem/3190)
✅ 백준: 선 긋기(https://www.acmicpc.net/problem/2170)
✅ 백준: 직사각형과 쿼리(https://www.acmicpc.net/problem/14846)

231121 김승희 제출

---

231121/김지희/BOJ_3190_김지희.java
231121/김지희/PRG_12914_김지희.java
231121/김지희/PRG_12953_김지희.java
231121/김지희/PRG_131127_김지희.java

✅ 백준(공통문제): 뱀 (https://www.acmicpc.net/problem/3190)
✅ 프로그래머스: 할인행사(https://school.programmers.co.kr/learn/courses/30/lessons/131127)
✅ 프로그래머스: N개의 최소공배수(https://school.programmers.co.kr/learn/courses/30/lessons/12953)
✅ 프로그래머스: 멀리 뛰기(https://school.programmers.co.kr/learn/courses/30/lessons/12914)

231121 김지희 제출

---

231121/백자민/BOJ_3190_백자민.java
231121/백자민/PRG_118670_백자민.java
231121/백자민/PRG_81302_백자민.java

✅ 백준(공통문제): 뱀 (https://www.acmicpc.net/problem/3190)
✅ 프로그래머스: 거리두기 확인하기 (https://school.programmers.co.kr/learn/courses/30/lessons/81302)
✅ 프로그래머스: 행렬과 연산 (https://school.programmers.co.kr/learn/courses/30/lessons/118670)
❌ 프로그래머스: 미로 탈출 (https://school.programmers.co.kr/learn/courses/30/lessons/81304)

231121 백자민 제출

---

231121/김아린/BOJ_뱀_김아린.java

✅ 백준 : 뱀(https://www.acmicpc.net/problem/3190)
✅ 프로그래머스 : 불량 사용자(https://school.programmers.co.kr/learn/courses/30/lessons/64064)
✅ 프로그래머스 : 성격 유형 검사하기(https://school.programmers.co.kr/learn/courses/30/lessons/118666)

231121 김아린 제출

---

231128/김승희/BOJ_2195_김승희.java
231128/김승희/BOJ_3190_김승희.java
231128/김승희/PRG_등산코스정하기_김승희.java

✅ 백준(공통문제): 댄스파티(https://www.acmicpc.net/problem/2831)
✅ 백준: 문자열 복사(https://www.acmicpc.net/problem/2195)
✅ 프로그래머스: 등산코스 정하기(https://school.programmers.co.kr/learn/courses/30/lessons/118669)

231128 김승희 제출

---

231121/김아린/PRG_불량사용자_김아린.java
231121/김아린/PRG_성격유형검사하기_김아린.java
231128/김아린/BOJ_2831_김아린.java
231128/김아린/PRG_118668_김아린.java
231128/김아린/PRG_118669_김아린.java

(+ 저번에 커밋 누락했던 것도 포함되어있음)
✅ 백준 : 댄스 파티(https://www.acmicpc.net/problem/2831)
✅ 프로그래머스 : 코딩 테스트 공부
(https://school.programmers.co.kr/learn/courses/30/lessons/118668)
✅ 프로그래머스 : 등산 코스 정하기(https://school.programmers.co.kr/learn/courses/30/lessons/118669)

231128 김아린 제출

---

231128/백자민/BOJ_2831_백자민.java
231128/백자민/PRG_150367_백자민.java
231128/백자민/PRG_81304_백자민.java
231205/백자민/BOJ_14499_백자민.java
231205/백자민/BOJ_16637_백자민.java
231205/백자민/BOJ_6087_백자민.java

✅ 백준(공통문제): 레이저 통신 (https://www.acmicpc.net/problem/6087)
✅ 백준: 주사위 굴리기 (https://www.acmicpc.net/problem/14499)
✅ 백준: 괄호 추가하기 (https://www.acmicpc.net/problem/16637)
저번주에 못올린 파일도 올립니당

231205 백자민 제출

---

231212/백자민/BOJ_14503_백자민.java
231212/백자민/BOJ_15684_백자민.java
231212/백자민/BOJ_16234_백자민.java
231212/백자민/BOJ_2467_백자민.java

✅ 백준(공통문제): 용액 (https://www.acmicpc.net/problem/2467)
✅ 백준: 인구 이동 (https://www.acmicpc.net/problem/16234)
✅ 백준: 사다리 조작 (https://www.acmicpc.net/problem/15684)
✅ 백준: 로봇 청소기 (https://www.acmicpc.net/problem/14503)

231212 백자민 제출

---

231212/김승희/BOJ_2268_김승희.java
231212/김승희/BOJ_5676_김승희.java

❌ 백준(공통문제): 용액 (https://www.acmicpc.net/problem/2467)
✅ 백준: 음주코딩 (https://www.acmicpc.net/problem/5676)
✅ 백준: 수들의 합7 (https://www.acmicpc.net/problem/2268)

231212 김승희 제출

---

231212/김아린/BOJ_2467_김아린.java
231212/김아린/BOJ_2473_김아린.java
231212/김아린/PRG_178870_김아린.java
231212/김아린/PRG_42885_김아린.java

✅ 프로그래머스 : 구명보트
(https://school.programmers.co.kr/learn/courses/30/lessons/42885)
✅ 프로그래머스 : 구명보트연속된 부분 수열의 합(https://school.programmers.co.kr/learn/courses/30/lessons/178870)
✅ 백준 : 용액(https://www.acmicpc.net/problem/2467)
✅ 백준 : 세 용액(https://www.acmicpc.net/problem/2473)

231212 김아린 제출

---

231219/백자민/BOJ_13549_백자민.java
231219/백자민/BOJ_15989_백자민.java
231219/백자민/BOJ_17836_백자민.java
231219/백자민/BOJ_21921_백자민.java

✅ 백준(공통문제): 공주님을 구해라! (https://www.acmicpc.net/problem/17836)
✅ 백준: 1,2,3 더하기 4 (https://www.acmicpc.net/problem/15989)
✅ 백준: 블로그 (https://www.acmicpc.net/problem/21921)
✅ 백준: 숨바꼭질 (https://www.acmicpc.net/problem/13549)

231219 백자민 제출

---

231226/백자민/BOJ_1062_백자민.java
231226/백자민/BOJ_1976_백자민.java
231226/백자민/BOJ_2504_백자민.java

✅ 백준(공통문제): 여행 가자(https://www.acmicpc.net/problem/1976)
✅ 백준: 괄호의 값(https://www.acmicpc.net/problem/2054)
✅ 백준: 가르침(https://www.acmicpc.net/problem/1062)

231226 백자민 제출

---

231226/BOJ_1976_김아린.java

✅ 백준 : 여행 가자(https://www.acmicpc.net/problem/1976)

231226 김아린 제출

---

240102/김승희/BOJ_17836_김승희.java
240102/김승희/BOJ_20922_김승희.java
240102/김승희/BOJ_2589_김승희.java

✅ 백준(공통문제): 공주님을 구해라! (https://www.acmicpc.net/problem/17836)
✅ 백준: 보물섬(https://www.acmicpc.net/problem/2589)
✅ 백준: 겹치는 건 싫어 (https://www.acmicpc.net/problem/20922)

240102 김승희 제출

---

240109/백자민/BOJ_1038_백자민.java
240109/백자민/BOJ_1253_백자민.java
240109/백자민/BOJ_12886_백자민.java
240109/백자민/BOJ_1700_백자민.java

✅ 백준(공통문제): 좋다(https://www.acmicpc.net/problem/1253)
✅ 백준: 멀티탭 스케줄링(https://www.acmicpc.net/problem/1700)
✅ 백준: 돌 그룹(https://www.acmicpc.net/problem/12886)
✅ 백준: 감소하는 수(https://www.acmicpc.net/problem/1038)

230109 백자민 제출

---

240109/김아린/BOJ_1253_김아린.java
240109/김아린/BOJ_1806_김아린.java
240109/김아린/BOJ_20922_김아린.java
240109/김아린/BOJ_22862_김아린.java
240109/김아린/PRG_67258_김아린.java

✅ 백준 : 좋다(https://www.acmicpc.net/problem/1253)
✅ 프로그래머스 : 보석 쇼핑(https://school.programmers.co.kr/learn/courses/30/lessons/67258)
✅ 백준 : 겹치는 건 싫어(https://www.acmicpc.net/problem/20922)
✅ 백준 : 가장 긴 짝수 연속한 부분 수열 (large)(https://www.acmicpc.net/problem/22862)
✅ 백준 : 부분합(https://www.acmicpc.net/problem/1806)

240109 김아린 제출

---

240109/김승희/BOJ_1253_김승희.java
240109/김승희/BOJ_1389_김승희.java

✅ 백준 : 좋다(https://www.acmicpc.net/problem/1253)
✅ 백준 : 케빈베이컨법칙(https://www.acmicpc.net/problem/1389)

240109 김승희 제출

---

240116/김승희/BOJ_2470_김승희.java
240116/김승희/CDT_1차원바람_김승희.java
240116/김승희/CDT_돌잘치우기_김승희.java
240116/김승희/CDT_트로미노_김승희.java

✅ 코드트리: 1차원 바람 (https://www.codetree.ai/missions?missionId=2)
✅ 코드트리: 트로미노 (https://www.codetree.ai/missions?missionId=2)
✅ 코드트리: 돌 잘 치우기 (https://www.codetree.ai/missions?missionId=2)
✅ 백준: 두 용액 (https://www.acmicpc.net/problem/2470)

240116 김승희 제출

---

240116/백자민/CDT_아름다운수_백자민.java
240116/백자민/CDT_정수사각형차이의최소2_백자민.java
240116/백자민/CDT_정수사각형최장증가수열_백자민.java

✅ 코드트리: 아름다운 수(https://www.codetree.ai/missions/2/problems/beautiful-number?&utm_source=clipboard&utm_medium=text)
✅ 코드트리: 정수 사각형 차이의 최소 2(https://www.codetree.ai/missions/2/problems/minimum-difference-on-the-integer-grid-2?&utm_source=clipboard&utm_medium=text)
✅ 코드트리: 정수 사각형 최장 증가 수열(https://www.codetree.ai/missions/2/problems/lis-on-the-integer-grid?&utm_source=clipboard&utm_medium=text)

230116 백자민 제출

---

240116/김아린/BOJ_11660_김아린.java
240116/김아린/BOJ_14846_김아린.java
240116/김아린/BOJ_15486_김아린.java
240116/김아린/BOJ_17485_김아린.java
240116/김아린/BOJ_1749_김아린.java
240116/김아린/BOJ_20440_김아린.java

✅ 백준 : 구간 합 구하기5(https://www.acmicpc.net/problem/11660)
✅ 백준 : 직사각형과 쿼리(https://www.acmicpc.net/problem/14846)
✅ 백준 : 점수따먹기(https://www.acmicpc.net/problem/1749)
✅ 백준 : 🎵니가 싫어 싫어 너무 싫어 싫어 오지 마 내게 찝쩍대지마🎵 - 1(https://www.acmicpc.net/problem/20440)
✅ 백준 : 퇴사2(https://www.acmicpc.net/problem/15486)
✅ 백준 : 진우의 달 여행 (Large)(https://www.acmicpc.net/problem/17485)

240116 김아린 제출

---

240123/백자민/BOJ_2671_백자민.java

✅ 백준(공통문제): 잠수함식별(https://www.acmicpc.net/problem/2671)

240123 백자민 제출

---

240123/김승희/BOJ_2671_김승희.java
240123/김승희/CDT_xor결과최대만들기_김승희.java
240123/김승희/CDT_강력한폭발_김승희.java
240123/김승희/CDT_벽짚고미로탈출하기_김승희.java

✅ 코드트리: 강력한 폭발 (https://www.codetree.ai/missions?missionId=2)
✅ 코드트리: xor 결과 최대 만들기 (https://www.codetree.ai/missions?missionId=2)
✅ 코드트리: 벽 짚고 미로 탈출하기 (https://www.codetree.ai/missions?missionId=2)
✅ 백준: 잠수함식별 (https://www.acmicpc.net/problem/2671)

240123 김승희 제출

---

240123/김아린/BOJ_2671_김아린.java
240123/김아린/BOJ_3107_김아린.java

✅ 백준 : 잠수함식별(https://www.acmicpc.net/problem/2671)
✅ 백준 : IPv6(https://www.acmicpc.net/problem/3107)

240123 김아린 제출

---

240130/백자민/BOJ_2590_백자민.java
240130/백자민/CDT_강력한폭발_백자민.py
240130/백자민/CDT_안전지대_백자민.py

✅ 백준(공통문제): 색종이(https://www.acmicpc.net/problem/2590)
✅ 코드트리: 안전 지대(https://www.codetree.ai/missions/2/problems/comfort-zone/description)
✅ 코드트리: 강력한 폭발(https://www.codetree.ai/missions/2/problems/strong-explosion/description)
❌ 코드트리: 주사위 던지기(https://www.codetree.ai/missions/2/problems/roll-a-dice/description)

240130 백자민 제출

---

240130/김승희/BOJ_2590_김승희.java
240130/김승희/CDT_수정_수집하기_김승희.java
240130/김승희/CDT_적절하게_숫자를_변경하기_김승희.java
240130/김승희/CDT_패턴매칭_김승희.java

✅ 코드트리: 패턴매칭 (https://www.codetree.ai/missions?missionId=2)
✅ 코드트리: 적절하게 숫자를 변경하기 (https://www.codetree.ai/missions?missionId=2)
✅ 코드트리: 수정 수집하기 (https://www.codetree.ai/missions?missionId=2)
✅ 백준: 색종이 (https://www.acmicpc.net/problem/2590)

240130 김승희 제출

---

240206/김승희/BOJ_14391_김승희.java
240206/김승희/CDT_미래가보이는가위바위보_김승희.java
240206/김승희/CDT_범위내에있는점의수2_김승희.java
240206/김승희/CDT_삼오무_김승희.java
240206/김승희/CDT_점개수세기2_김승희.java

❌ 백준(공통문제): 종이 조각 (https://www.acmicpc.net/problem/14391)
✅ 코드트리: 삼 오 무 (https://www.codetree.ai/missions/8/problems/three-five-moo/description)
✅ 코드트리: 미래가 보이는 가위바위보 (https://www.codetree.ai/missions/8/problems/rock-paper-scissors-to-see-the-future/description)
✅ 코드트리: 범위 내에 있는 점의 수 2 (https://www.codetree.ai/missions/8/problems/the-number-of-points-within-the-range-2/description)
✅ 코드트리: 점 개수 세기 2 (https://www.codetree.ai/missions/8/problems/count-number-of-points-2/description)

240206 김승희 제출

---

240206/백자민/BOJ_14391_백자민.java
240206/백자민/CDT_겹치지않게선분고르기2_백자민.java
240206/백자민/CDT_합쳐지는구슬들_백자민.java

✅ 백준(공통문제): 종이 조각 (https://www.acmicpc.net/problem/14391)
✅ 코드트리: 겹치지 않게 선분 고르기2 (https://www.codetree.ai/missions/2/problems/select-segments-without-overlap-2/description)
✅ 코드트리: 합쳐지는 구슬들 (https://www.codetree.ai/missions/2/problems/merge-marbles/description?&utm_source=clipboard&utm_medium=text)

240206 백자민 제출

---

240206/김아린/BOJ_14391_김아린.java
240206/김아린/BOJ_3980_김아린.java
240206/김아린/PRG_152995_김아린.java
240206/김아린/PRG_250136_김아린.java

✅ 백준 : 종이 조각(https://www.acmicpc.net/problem/14391)
✅ 백준 : 선발 명단(https://www.acmicpc.net/problem/3980)
✅ 프로그래머스 : 석유 시추(https://school.programmers.co.kr/learn/courses/30/lessons/250136)
✅ 프로그래머스 : 인사 고과(https://school.programmers.co.kr/learn/courses/30/lessons/152995)

240206 김아린 제출

---

240220/김승희/BOJ_11964_김승희.java
240220/김승희/CDT_격자칠하기2_김승희.java
240220/김승희/CDT_색칠된칸으로면이동2_김승희.java
240220/김승희/CDT_자연수2분의M개의쌍_김승희.java

✅ 백준 : Fruit Feast(https://www.acmicpc.net/problem/11964)
✅ 코드트리: 자연수 M/2개의 쌍 (https://www.codetree.ai/missions/8/problems/m2-pairs-of-natural-numbers?&utm_source=clipboard&utm_medium=text)
✅ 코드트리: 격자 칠하기 2 (https://www.codetree.ai/missions/8/problems/painting-the-grid-2?&utm_source=clipboard&utm_medium=text)
✅ 코드트리: 색칠된 칸으로만 이동 2 (https://www.codetree.ai/missions/8/problems/move-to-the-colored-space-only-2?&utm_source=clipboard&utm_medium=text)

240220 : 김승희 제출

---

240227/백자민/BOJ_14226_백자민.java
240227/백자민/CDT_이상한폭탄_백자민.java

✅ 백준(공통문제): 이모티콘(https://www.acmicpc.net/problem/14226)
✅ 코드트리: 이상한 폭탄(https://www.codetree.ai/missions/8/problems/strange-bomb?&utm_source=clipboard&utm_medium=text)

240227 백자민 제출

---

240227/김아린/BOJ_14226_김아린.java
240227/김아린/BOJ_1501_김아린.java

✅ 백준 : 이모티콘(https://www.acmicpc.net/problem/14226)
✅ 백준 : 영어 읽기(https://www.acmicpc.net/problem/1501)

240227 김아린 제출

---

240305/백자민/BOJ_1300_백자민.java
240305/백자민/BOJ_16938_백자민.java
240305/백자민/CDT_격자칠하기2_백자민.java

✅ 백준(공통문제): 캠프 준비(https://www.acmicpc.net/problem/16938)
✅ 백준: K번째 수(https://www.acmicpc.net/problem/1300)
✅ 코드트리: 격자 칠하기 2(https://www.codetree.ai/missions/8/problems/painting-the-grid-2?&utm_source=clipboard&utm_medium=text)

230305 백자민 제출

---

240305/김아린/BOJ_1477_김아린.java
240305/김아린/BOJ_16938_김아린.java

✅ 백준 : 캠프 준비(https://www.acmicpc.net/problem/16938)
✅ 백준 : 휴게소 세우기(https://www.acmicpc.net/problem/1477)

240305 김아린 제출

---

240312/백자민/BOJ_1967_백자민.java
240312/백자민/BOJ_2812_백자민.java
240312/백자민/CDT_트리판별_백자민.java

✅ 백준(공통문제): 크게 만들기(https://www.acmicpc.net/problem/2812)
✅ 백준: 트리의 지름(https://www.acmicpc.net/problem/1967)
✅ 코드트리: 트리 판별(https://www.codetree.ai/missions/9/problems/tree-identification?&utm_source=clipboard&utm_medium=text)

240312 백자민 제출

---

240319/김아린/BOJ_1941_김아린.java
240319/김아린/PRG_77486_김아린.java

✅ 프로그래머스 : 다단계 칫솔 판매(https://school.programmers.co.kr/learn/courses/30/lessons/77486)
✅ 백준 : 소문난 칠공주(https://www.acmicpc.net/problem/1941)

240319 김아린 제출

---

240319/백자민/CDT_노드의인접한공통조상_백자민.java
240319/백자민/CDT_인접하지않게색칠하기_백자민.java
240319/백자민/PRG_258705_백자민.java

✅ 프로그래머스: 산 모양 타일링(https://school.programmers.co.kr/learn/courses/30/lessons/258705#qna)
✅ 코드트리: 노드의 인접한 공통 조상(https://www.codetree.ai/missions/9/problems/adjacent-common-ancestor-nodes?&utm_source=clipboard&utm_medium=text)
✅ 코드트리: 인접하지 않게 색칠하기(https://www.codetree.ai/missions/9/problems/coloring-not-adjacently?&utm_source=clipboard&utm_medium=text)

240319 백자민 제출

---

240326/백자민/BOJ_16562_백자민.java
240326/백자민/CDT_LRTechnique_백자민.java
240326/백자민/PRG_12911_백자민.java

✅ 백준(공통문제): 친구비 (https://www.acmicpc.net/problem/16562)
✅ 프로그래머스: 다음 큰 숫자 (https://school.programmers.co.kr/learn/courses/30/lessons/12911)
✅ 코드트리: 마라톤 중간에 택시타기 (https://www.codetree.ai/missions/8/problems/taking-a-taxi-in-the-middle-of-the-marathon?&utm_source=clipboard&utm_medium=text)

240326 백자민 제출

---

240403/백자민/BOJ_2457_백자민.java
240403/백자민/CDT_적석과흑석2_백자민.java
240403/백자민/CDT_최대숫자만들기_백자민.java

✅ 백준(공통문제): 공주님의 정원 (https://www.acmicpc.net/problem/2457)
✅ 코드트리: 적석과 흑석 2 (https://www.codetree.ai/missions/8/problems/red-stone-and-black-stone-2?&utm_source=clipboard&utm_medium=text)
✅ 코드트리: 최대 숫자 만들기 (https://www.codetree.ai/missions/8/problems/make-biggest-num?&utm_source=clipboard&utm_medium=text)

240403 백자민 제출

---

.gitignore
240403/김아린/BOJ_1202_김아린.java
240403/김아린/BOJ_2457_김아린.java

✅ 백준 : 공주님의 정원(https://www.acmicpc.net/problem/2457)
✅ 백준 : 보석 도둑(https://www.acmicpc.net/problem/1202)

240403 김아린 제출

---

240409/백자민/BOJ_20366_백자민.java
240409/백자민/CDT_1차원바람_백자민.java
240409/백자민/CDT_쪼개어배낭채우기구현_백자민.java

✅ 백준(공통문제): 같이 눈사람 만들래? (https://www.acmicpc.net/problem/20366)
✅ 코드트리: 쪼개어 배낭 채우기 구현 (https://www.codetree.ai/missions/8/problems/implement-fractional-knapsack?&utm_source=clipboard&utm_medium=text)
✅ 코드트리: 1차원 바람 (https://www.codetree.ai/missions/2/problems/The-1D-wind-blows?&utm_source=clipboard&utm_medium=text)

240409 백자민 제출

---

240416/백자민/BOJ_16197_백자민.java
240416/백자민/CDT_십자모양폭발_백자민.java
240416/백자민/CDT_왕실의기사대결_백자민.java

✅ 백준(공통문제): 두 동전(https://www.acmicpc.net/problem/16197)
✅ 코드트리: 십자 모양 폭발(https://www.codetree.ai/missions/2/problems/cross-shape-bomb?&utm_source=clipboard&utm_medium=text)
✅ 코드트리: 왕실의 기사 대결(https://www.codetree.ai/training-field/frequent-problems/problems/royal-knight-duel?&utm_source=clipboard&utm_medium=text)

240416 백자민 제출

---

240423/백자민/BOJ_2109_백자민.java
240423/백자민/CDT_다른괄호로이동하기_백자민.java

✅ 백준(공통문제): 순회강연(https://www.acmicpc.net/problem/2109)
✅ 코드트리: 다른 괄호로 이동하기(https://www.codetree.ai/missions/8/problems/move-to-another-parenthesis?&utm_source=clipboard&utm_medium=text)

240423 백자민 제출

---

240430/백자민/BOJ_12869_백자민.java
240430/백자민/CDT_가장긴좌우대칭인문자열찾기2_백자민.java

✅ 백준(공통문제): 뮤탈리스크 (https://www.acmicpc.net/problem/12869)
✅ 코드트리: 가장 긴 좌우 대칭인 문자열 찾기2 (https://www.codetree.ai/missions/9/problems/longest-palindrome-2?&utm_source=clipboard&utm_medium=text)

240430 백자민 제출

---

240430/김아린/BOJ_12869_김아린.java
240430/김아린/BOJ_5875_김아린.java

✅ 백준 : 뮤탈리스크(https://www.acmicpc.net/problem/12869)
✅ 백준 : 오타(https://www.acmicpc.net/problem/5875)

240430 김아린 제출

---

240507/백자민/BOJ_15831_백자민.java
240507/백자민/CDT_검색어와접두사_백자민.java

✅ 백준(공통문제): 준표의 조약돌(https://www.acmicpc.net/problem/15831)
✅ 코드트리: 검색어와 접두사(https://www.codetree.ai/missions/9/problems/search-terms-and-prefixes?&utm_source=clipboard&utm_medium=text)

240507 백자민 제출

---

240507/김아린/BOJ_15831_김아린.java
240507/김아린/BOJ_20164_김아린.java

✅ 백준 : 준표의 조약돌(https://www.acmicpc.net/problem/15831)
✅ 백준 : 홀수 홀릭 호석(https://www.acmicpc.net/problem/20164)

240507 김아린 제출

---

240514/백자민/BOJ_1005_백자민.java
240514/백자민/CDT_사이클판별_백자민.java

✅ 백준(공통문제): ACM Craft(https://www.acmicpc.net/problem/1005)
✅ 코드트리: 사이클 판별(https://www.codetree.ai/missions/9/problems/detect-cycle?&utm_source=clipboard&utm_medium=text)

240514 백자민 제출

---

240514/김아린/BOJ_1005_김아린.java
240514/김아린/PRG_161988_김아린.java

✅ 백준 : ACM Craft(https://www.acmicpc.net/problem/1005)
✅ 프로그래머스 : 연속 펄스 부분 수열의 합
(https://school.programmers.co.kr/learn/courses/30/lessons/161988)

240514 김아린 제출

---

240521/BOJ_20665_김아린.java
240521/BOJ_6209_김아린.java

✅ 백준 : 독서실 거리두기(https://www.acmicpc.net/problem/20665)
✅ 백준 : 제자리 멀리뛰기(https://www.acmicpc.net/problem/6209)

240521 김아린 제출

---

240521/백자민/BOJ_6209_백자민.java
240521/백자민/CDT_길이가무한대인수평선트랙_백자민ㄴ.java
240521/백자민/CDT_연속한K개의숫자_백자민.java

✅ 백준(공통문제): 제자리 멀리뛰기(https://www.acmicpc.net/problem/6209)
✅ 코드트리: 길이가 무한대인 수평선 트랙(https://www.codetree.ai/missions/8/problems/horizontal-track-with-infinite-length?&utm_source=clipboard&utm_medium=text)
✅ 코드트리: 연속한 K개의 숫자(https://www.codetree.ai/missions/8/problems/k-numbers-in-a-row?&utm_source=clipboard&utm_medium=text)

240521 백자민 제출

---

240528/백자민/BOJ_10775_백자민.java
240528/백자민/CDT_초대장과번호표_백자민.java

✅ 백준(공통문제): 공항(https://www.acmicpc.net/problem/10775)
✅ 코드트리: 초대장과 번호표(https://www.codetree.ai/missions/8/problems/invitation-and-number-tag?&utm_source=clipboard&utm_medium=text)

240528 백자민 제출

---

240604/백자민/BOJ_22860_백자민.java

✅ 백준(공통문제): 폴더 정리(small) (https://www.acmicpc.net/problem/22860)

240604 백자민 제출

---

240604/김아린/BOJ_22860_김아린.java

✅ 백준 : 폴더 정리 (small)(https://www.acmicpc.net/problem/22860)

240604 김아린 제출

---

240611/김아린/BOJ_10427_김아린.java
240611/김아린/BOJ_1520_김아린.java

✅ 백준 : 내리막 길 (https://www.acmicpc.net/problem/1520)
✅ 백준 : 빚 (https://www.acmicpc.net/problem/10427)

240611 김아린 제출

---

240611/백자민/BOJ_1520_백자민.java
240611/백자민/CDT_편집거리_백자민.java

✅ 백준(공통문제): 내리막 길 (https://www.acmicpc.net/problem/1520)
✅ 코드트리: 편집 거리 (https://www.codetree.ai/missions/2/problems/edit-distance?&utm_source=clipboard&utm_medium=text)

240611 백자민 제출

---

240618/백자민/BOJ_16973_백자민.java
240618/백자민/CDT_겹치는원소가적은부분수열_백자민.java

✅ 백준(공통문제): 직사각형 탈출 (https://www.acmicpc.net/problem/16973)
✅ 코드트리: 겹치는 원소가 적은 부분 수열 (https://www.codetree.ai/missions/8/problems/subsequences-with-few-overlapping-elements?&utm_source=clipboard&utm_medium=text)

240618 백자민 제출

---

240625/백자민/BOJ_19538_백자민.java
240625/백자민/CDT_계단오르기2_백자민.java

✅ 백준(공통문제): 루머 (https://www.acmicpc.net/problem/19538)
✅ 코드트리: 계단 오르기 2 (https://www.codetree.ai/missions/2/problems/climbing-stairs-2?&utm_source=clipboard&utm_medium=text)

240625 백자민 제출

---

240702/백자민/BOJ_6068_백자민.java
240702/백자민/CDT_홍팀과백팀_백자민.java

✅ 백준(공통문제): 시간 관리하기 (https://www.acmicpc.net/problem/6068)
✅ 코드트리: 홍팀과 백팀 (https://www.codetree.ai/missions/9/problems/red-team-and-white-team?&utm_source=clipboard&utm_medium=text)

240702 백자민 제출

---

240709/백자민/BOJ_14238_백자민.java
240709/백자민/CDT_최대직사각형합_백자민.java

✅ 백준(공통문제): 출근기록 (https://www.acmicpc.net/problem/14238)
✅ 코드트리: 최대 직사각형 합 (https://www.codetree.ai/missions/8/problems/max-rect-sum-in-grid?&utm_source=clipboard&utm_medium=text)

240709 백자민 제출

---

240716/김아린/BOJ_2143_김아린.java

✅ 백준 : 두 배열의 합(https://www.acmicpc.net/problem/2143)

240716 김아린 제출

---

240716/BOJ_2143_백자민.py

✅ 백준(공통문제): 두 배열의 합(https://www.acmicpc.net/problem/2143)

240716 백자민 제출

---

240724/BOJ_2176_김아린.java

✅ 백준 : 합리적인 이동경로(https://www.acmicpc.net/problem/2176)

240724 김아린 제출

---

240724/백자민/BOJ_2176_백자민.py
240724/백자민/CDT_아름다운수_백자민.py

✅ 백준(공통문제): 합리적인 이동경로(https://www.acmicpc.net/problem/2176)
✅ 코드트리: 아름다운 수(https://www.codetree.ai/missions/2/problems/beautiful-number?&utm_source=clipboard&utm_medium=text)

240724 백자민 제출

---

240807/김아린/BOJ_12969_김아린.java
240807/김아린/BOJ_1799_김아린.java

✅ 백준 : ABC(https://www.acmicpc.net/problem/12969)
✅ 백준 : 비숍(https://www.acmicpc.net/problem/1799)

240807 김아린 제출

---

240814/백자민/BOJ_3015_백자민.py

✅ 백준(공통문제): 오아시스 재결합(https://www.acmicpc.net/problem/3015)

240814 백자민 제출

---

240814/김아린/BOJ_3015_김아린.java

✅ 백준 : 오아시스 재결합(https://www.acmicpc.net/problem/3015)

240814 김아린 제출

---

240821/백자민/BOJ_2180_백자민.py

✅ 백준(공통문제): 소방서의 고민(https://www.acmicpc.net/problem/2180)

240821 백자민 제출

---

240821/김아린/BOJ_2180_김아린.java

✅ 백준 : 소방서의 고민(https://www.acmicpc.net/problem/2180)

240821 김아린 제출

---

240828/김아린/BOJ_11003_김아린.java

✅ 백준 : 최솟값 찾기(https://www.acmicpc.net/problem/11003)

240828 김아린 제출

---

240904/김아린/BOJ_3197_김아린.java

✅ 백준 : 백조의 호수(https://www.acmicpc.net/problem/3197)

240904 김아린 제출

---

240904/백자민/BOJ_3197_백자민.py

✅ 백준(공통문제): 백조의 호수(https://www.acmicpc.net/problem/3197)

240904 백자민 제출

---

240911/백자민/BOJ_16496_백자민.py
240911/백자민/CDT_최단거리11_백자민.py

✅ 백준(공통문제): 큰 수 만들기(https://www.acmicpc.net/problem/16496)
✅ 코드트리: 최단 거리 11(https://www.codetree.ai/missions/8/problems/shortest-distance-11?&utm_source=clipboard&utm_medium=text)

240911 백자민 제출

---

240911/김아린/BOJ_16496_김아린.java
240911/김아린/BOJ_17951_김아린.java

✅ 백준 : 큰 수 만들기(https://www.acmicpc.net/problem/16496)
✅ 백준 : 흩날리는 시험지 속에서 내 평점이 느껴진거야(https://www.acmicpc.net/problem/17951)

240911 김아린 제출

---

240918/백자민/BOJ_1981_백자민.py

✅ 백준(공통문제): 배열에서 이동(https://www.acmicpc.net/problem/1981)

240918 백자민 제출

---

240918/김아린/BOJ_1981_김아린.java
240918/김아린/BOJ_2613_김아린.java

✅ 백준 : 숫자구슬(https://www.acmicpc.net/problem/2613)
✅ 백준 : 배열에서 이동(https://www.acmicpc.net/problem/1981)

240918 김아린 제출

---

240925/김아린/BOJ_23291_김아린.java

❌ 백준 : 어항 정리(https://www.acmicpc.net/problem/23291)

240925 김아린 제출

---

240925/백자민/BOJ_23291_백자민.py
240925/백자민/CDT_좌우반전시키기_백자민.py

✅ 백준(공통문제): 어항정리(https://www.acmicpc.net/problem/23291)
✅ 코드트리: 좌우 반전시키기(https://www.codetree.ai/missions/8/problems/flip-left-and-right?&utm_source=clipboard&utm_medium=text)

240925 백자민 제출

---

241002/백자민/BOJ_2887_백자민.py

✅ 백준(공통문제): 행성 터널(https://www.acmicpc.net/problem/2887)

241002 백자민 제출

---

241009/김아린/BOJ_17831_김아린.java

✅ 백준(공통문제): 대기업 승범이네(https://www.acmicpc.net/problem/17831)

241009 김아린 제출

---

241023/백자민/BOJ_1562_백자민.py

✅ 백준(공통문제): 계단 수(https://www.acmicpc.net/problem/1562)

241023 백자민 제출

---

241023/김아린/BOJ_1562_김아린.java

✅ 백준(공통문제): 계단 수(https://www.acmicpc.net/problem/1562)

241023 김아린 제출

---

241106/김아린/BOJ_8980_김아린.java

✅ 백준(공통문제): 택배(https://www.acmicpc.net/problem/8980)

241106 김아린 제출

---

241106/백자민/BOJ_8980_백자민.py

✅ 백준(공통문제): 택배(https://www.acmicpc.net/problem/8980)

241106 백자민 제출

---

241113/백자민/BOJ_5022_백자민.py

✅ 백준(공통문제): 연결(https://www.acmicpc.net/problem/5022)

241113 백자민 제출

---

241113/김아린/BOJ_5022_김아린.java

✅ 백준(공통문제): 연결(https://www.acmicpc.net/problem/5022)

241113 김아린 제출

---

241120/백자민/BOJ_7579_백자민.py

✅ 백준(공통문제): 앱(https://www.acmicpc.net/problem/7579)

241120 백자민 제출

---

241120/김아린/BOJ_7579_김아린.java

✅ 백준(공통문제): 앱(https://www.acmicpc.net/problem/7579)

241120 김아린 제출

---

241204/백자민/BOJ_2632_백자민.py

✅ 백준(공통문제): 피자판매(https://www.acmicpc.net/problem/2632)

241204 백자민 제출

---

241204/김아린/BOJ_2632_김아린.java

✅ 백준(공통문제): 피자판매(https://www.acmicpc.net/problem/2632)

241204 김아린 제출

---

241211/백자민/BOJ_5214_백자민.py

✅ 백준(공통문제): 환승(https://www.acmicpc.net/problem/5214)

241213 백자민 제출

---

241209/김아린/BOJ_13975_김아린.java
241209/김아린/BOJ_5214_김아린.java

✅ 백준(공통문제): 환승(https://www.acmicpc.net/problem/5214)
✅ 백준(공통문제): 파일 합치기 3(https://www.acmicpc.net/problem/13975)

241211 김아린 제출

---

250108/백자민/BOJ_1781_백자민.py

✅ 백준(공통문제): 컵라면(https://www.acmicpc.net/problem/1781)

250108 백자민 제출

---

250108/김아린/BOJ_1781_김아린.java
250108/김아린/BOJ_21758_김아린.java

✅ 백준(공통문제): 컵라면(https://www.acmicpc.net/problem/1781)
✅ 백준:  꿀 따기(https://www.acmicpc.net/problem/21758)

250108 김아린 제출

---

250123/BOJ_18870_김아린.java
250123/BOJ_1939_김아린.java

✅ 백준: 좌표 압축(https://www.acmicpc.net/problem/18870)
✅ 백준(공통문제): 중량제한(https://www.acmicpc.net/problem/1939)

250123 김아린 제출

---

250204/김아린/BOJ_3151_김아린.java

✅ 백준(공통문제): 합이 0(https://www.acmicpc.net/problem/3151)

250204 김아린 제출

---

250204/백자민/BOJ_3151_백자민.py

✅ 백준(공통문제): 합이 0(https://www.acmicpc.net/problem/3151)

250204 백자민 제출

---

250212/벡자민/BOJ_9527_백자민.py

✅ 백준(공통문제): 1의 개수 세기(https://www.acmicpc.net/problem/9527)

250212 백자민 제출

---

250212/김아린/BOJ_9527_김아린.java

❌ 백준(공통문제): 1의 개수 세기(https://www.acmicpc.net/problem/9527)
- 31%에서 틀림

250212 김아린 제출

---

250219/김아린/BOJ_1106_김아린.java

✅ 백준(공통문제): 호텔(https://www.acmicpc.net/problem/1106)

250219 김아린 제출

---

250219/백자민/BOJ_1106_백자민.py

✅ 백준(공통문제): 호텔(https://www.acmicpc.net/problem/1106)

250219 백자민 제출

---

250226/백자민/BOJ_1744_백자민.py

✅ 백준(공통문제): 수 묶기(https://www.acmicpc.net/problem/1744)

250226 백자민 제출

---

250305/백자민/BOJ_19942_백자민.py

✅ 백준(공통문제): 다이어트(https://www.acmicpc.net/problem/19942)

250305 백자민 제출

---

250305/김아린/BOJ_1522_김아린.java
250305/김아린/BOJ_19942_김아린.java

✅ 백준(공통문제): 다이어트(https://www.acmicpc.net/problem/19942)
✅ 백준: 문자열 교환(https://www.acmicpc.net/problem/1522)

250305 김아린 제출

---

250312/김아린/BOJ_2879_김아린.java

❌ 백준(공통문제): 코딩은 예쁘게(https://www.acmicpc.net/problem/2879)

250312 김아린 제출

---

250326/백자민/BOJ_2922_백자민.py

✅ 백준(공통문제): 즐거운 단어(https://www.acmicpc.net/problem/2922)

250326 백자민 제출

---

250409/김아린/BOJ_2096_김아린.java

✅ 백준(공통문제): 내려가기(https://www.acmicpc.net/problem/2096)

250409 김아린 제출

---

250409/BOJ_2096_백자민.py

✅ 백준(공통문제): 내려가기(https://www.acmicpc.net/problem/2096)

250409 백자민 제출

---

250416/김아린/BOJ_32069_김아린.java

✅ 백준(공통문제): 가로등(https://www.acmicpc.net/problem/32069)

240416 김아린 제출

---

2025/250502/백자민/BOJ_2258.py

✅ 백준(공통문제): 정육점(https://www.acmicpc.net/problem/2258)

250502 백자민 제출

---

2025/250509/김아린/BOJ_12764_김아린.java

✅ 백준(공통문제): 싸지방에 간 준하(https://www.acmicpc.net/problem/12764)

250509 김아린 제출

---

2025/250509/백자민/BOJ_12764_백자민.py

✅ 백준(공통문제): 싸지방에 간 준하(https://www.acmicpc.net/problem/12764)

250509 백자민 제출

---

2025/250516/백자민/BOJ_2151_백자민.py

✅ 백준(공통문제): 거울 설치(https://www.acmicpc.net/problem/2151)

250516 백자민 제출

---

2025/250516/김아린/BOJ_2151_김아린.java

✅ 백준(공통문제): 거울 설치(https://www.acmicpc.net/problem/2151)

add: boj 거울설치

---

2025/250522/김아린/boj_2141_김아린.js

✅ 백준(공통문제): 우체국(https://www.acmicpc.net/problem/2141)

250522 김아린 제출

---

2025/250530/김아린/BOJ_10653_김아린.java

✅ 백준(공통문제): 마라톤2(https://www.acmicpc.net/problem/10653)

250530 김아린 제출

---

2025/250621/김아린/BOJ_커플만들기.java

✅ 백준(공통문제): 커플 만들기(https://www.acmicpc.net/problem/1727)

250621 김아린 제출

---

2025/250629/백자민/BOJ_1202_백자민.py

✅ 백준: 보석 도둑(https://www.acmicpc.net/problem/1202)

250629 백자민 제출

---

2025/250706/백자민/BOJ_21943_백자민.py

✅ 백준(공통문제): 연산 최대로(https://www.acmicpc.net/problem/21943)

250706 백자민 제출

---

2025/250803/김아린/BOJ_20207_김아린.java

✅ 백준(필수 문제): 달력(https://www.acmicpc.net/problem/20207)

250803 김아린 제출

---

2025/250810/백자민/BOJ_1082_백자민.py

✅ 백준(필수 문제): 방 번호(https://www.acmicpc.net/problem/1082)

250810 백자민 제출

---

2025/250817/김아린/BOJ_9576_김아린.java

✅ 백준(필수 문제): 책 나눠주기(https://www.acmicpc.net/problem/9576)

250817 김아린 제출

---

2025/250831/백자민/BOJ_17265_백자민.py

✅ 백준(필수 문제): 나의 인생에는 수학과 함께(https://www.acmicpc.net/problem/17265)

250831 백자민 제출

---

2025/250914/김아린/BOJ_2295_김아린.java

✅ 백준(필수 문제): 세 수의 합(https://www.acmicpc.net/problem/2295)

250914 김아린 제출

---

2025/250921/백자민/BOJ_18234_백자민.py

✅ 백준(필수 문제): 당근 훔쳐 먹기(https://www.acmicpc.net/problem/18234)

250921 백자민 제출

---

2025/250928/백자민/BOJ_2157_백자민.py

✅ 백준(필수 문제): 여행(https://www.acmicpc.net/problem/2157)

250928 백자민 제출

---

2025/250928/김아린/BOJ_2157_김아린.java

✅ 백준(필수 문제): 여행(https://www.acmicpc.net/problem/2157)

250928 김아린 제출
